[tasks.pre-commit]
depends = ["no-n-a-r-f"]
run = "hk run pre-commit"

[tasks.prelint]

[tasks.postlint]

[tasks.game]
description = "Run the game"
run = "godot --path . --print-fps"

[tasks.godot]
description = "Run the Godot editor"
run = "(godot --path . --editor >& /dev/null &)"

[tasks.no-n-a-r-f]
description = "Check for the word N-A-R-F in the source code"
quiet = true
run = """
#!/usr/bin/env bash
forbidden='na'"rf"
if git --no-pager grep --ignore-case --perl-regexp \
  '\\'b"$forbidden"'\\'b
then
  printf '%s%s%s%s found in source code!\\n' "N" "A" "R" "F"
  exit 1
else
  : do nothing
fi
"""

[tools]
hk = "1.19.0"
pkl = "0.29.1"

[tools."ubi:gdquest/gdscript-formatter"]
rename_exe = "gdscript-formatter"
version = "0.14.0"
