[tasks.pre-commit]
run = "hk run pre-commit"

[tasks.prelint]

[tasks.postlint]

[tasks.game]
description = "Run the game"
run = "godot --path . --print-fps"

[tasks.godot]
description = "Run the Godot editor"
run = "(godot --path . --editor >& /dev/null &)"

[tools]
hk = "1.19.0"
pkl = "0.29.1"

[tools."ubi:gdquest/gdscript-formatter"]
rename_exe = "gdscript-formatter"
version = "0.14.0"
